services:
  frontend:
    image: alexandre78r/dev-frontend-portfolio:latest
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_IMAGE_URL=http://localhost:8000
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3
    depends_on:
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8001}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx-dev

volumes:
  wildcodehub-data:
  wildcodehub-data-test:

