events {}

http {
  include mime.types;

  server {
    listen 80;


    location /graphql {
      proxy_pass http://backend:4000;
    }

    location /api/ {
        proxy_pass http://backend:4000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /badge/ {
            proxy_pass http://backend:4000/badge/;

    }


    location /dynamic-images {
      proxy_pass http://backend:4000;
    }

    location /_next/webpack-hmr {
        proxy_pass http://frontend:3000/_next/webpack-hmr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
      proxy_pass http://frontend:3000;
    }
  }
}

