[
  {
    "id": "update-dev",
    "execute-command": "/home/ubuntu/apps/portfolio/portfolio-dev/fetch-and-deploy-dev.sh",
    "command-working-directory": "/home/ubuntu/apps/portfolio/portfolio-dev",
    "trigger-rule": {
      "match": {
        "type": "payload-hash-sha1",
        "secret": "",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
  },
  {
    "id": "update-main",
    "execute-command": "/home/ubuntu/apps/portfolio/portfolio/fetch-and-deploy-main.sh",
    "command-working-directory": "/home/ubuntu/apps/portfolio/portfolio",
    "trigger-rule": {
      "match": {
        "type": "payload-hash-sha1",
        "secret": "//TODO: add secret here",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
  },
  {
    "id": "update-dev-wildcodehub",
    "execute-command": "/home/ubuntu/apps/wildcodehub/dev-wildcodehub/fetch-and-deploy-dev.sh",
    "command-working-directory": "/home/ubuntu/apps/wildcodehub/dev-wildcodehub",
    "trigger-rule": {
      "match": {
        "type": "payload-hash-sha256",
        "secret": "//TODO: add secret here",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
  },
  {
    "id": "update-main-maintenance",
    "execute-command": "/home/ubuntu/apps/portfolio-maintenance/main-portfolio-maintenance-git/fetch-and-deploy-main.sh",
    "command-working-directory": "/home/ubuntu/apps/portfolio-maintenance/main-portfolio-maintenance",
    "trigger-rule": {
      "match": {
        "type": "payload-hash-sha1",
        "secret": "//TODO: add secret here",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
  },
]
