[
  {
    "id": "update-dev",
    "execute-command": "// TODO: add command to fetch and deploy main maintenance branch",
    "command-working-directory": "//TODO: add working directory for main maintenance branch",
    "trigger-rule": {
      "match": {
        "type": "payload-hash-sha1",
        "secret": "",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
  },
  {
    "id": "update-main",
    "execute-command": "// TODO: add command to fetch and deploy main maintenance branch",
    "command-working-directory": "//TODO: add working directory for main maintenance branch",
    "trigger-rule": {
      "match": {
        "type": "payload-hash-sha1",
        "secret": "//TODO: add secret here",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
  },
  {
    "id": "update-main-maintenance",
    "execute-command": "// TODO: add command to fetch and deploy main maintenance branch",
    "command-working-directory": "//TODO: add working directory for main maintenance branch",
    "trigger-rule": {
      "match": {
        "type": "payload-hash-sha1",
        "secret": "//TODO: add secret here",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
  },
]
