# .github/workflows/dev-client.yml
name: Compile and push profile APP staging 

# Controls when the workflow will run
on:
  pull_request:
    branches: ["dev"]
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Build
          
      - uses: docker/build-push-action@v4
        name: Build and push frontend
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dev-frontend-portfolio:latest
          build-args: 
            NEXT_PUBLIC_API_TOKEN: ${{ secrets.NEXT_PUBLIC_API_TOKEN }}

      - uses: docker/build-push-action@v4
        name: Build and push backend
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dev-backend-portfolio:latest

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        env:
          SECRET_KEY: ${{ secrets.WEBHOOK_SECRET_DEV }}
        run: |
          PAYLOAD='{"example": "data"}'
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha1 -hmac "$SECRET_KEY" | sed 's/^.* //')
          SIGNATURE="sha1=$SIGNATURE"

          curl -X POST -H "Content-Type: application/json" -H "X-Hub-Signature: $SIGNATURE" -d "$PAYLOAD" ${{ secrets.WEBHOOK_URL_DEV }}
